### PR TITLE
Added Start Date and End Date

### PR DESCRIPTION
**Pull request by gaurav24072002**
#63 and #51 
Added the section of Start Date and End Date of some programs but need to do more

### CODE REVIEW

**Review by vybhav72954 — CHANGES_REQUESTED** [review]
There is a small merge conflict because I recently deleted a few programs, would it be possible for you to resolve it?

**Comment by gaurav24072002** [comment]
can you please tell me what all changes you did so that I can solve it on mine or should I fork it again ??

**Comment by vybhav72954** [comment]
> can you please tell me what all changes you did so that I can solve it on mine or should I fork it again ??

I have a better idea, let me resolve the conflict from 

> can you please tell me what all changes you did so that I can solve it on mine or should I fork it again ??

No No, you need not do anything like that at all.
Do you use Discord, or can you drop your email here? I will guide you with the steps.

**Comment by gaurav24072002** [comment]
ok gaurav02maheshwari@gmail.com

**Comment by vybhav72954** [comment]
> ok [gaurav02maheshwari@gmail.com](mailto:gaurav02maheshwari@gmail.com)

Cool i will send you the instructions as soon as possible.

**Comment by gaurav24072002** [comment]
ok I'll do the changes as soon as I will get instruction..

**Comment by vybhav72954** [comment]
> ok I'll do the changes as soon as I will get instruction..

Check your Email

**Comment by vybhav72954** [comment]
@gaurav24072002 I have made the necessary changes and resolved the conflict.

But the next question is, are you planning to update the PR?

If not I will merge the changes in master at least for now.

**Comment by gaurav24072002** [comment]
Yes I have to add more start and end date of events in the readme.md file but you can merge till now but dont close the issue...ok

**Comment by vybhav72954** [comment]
@deepanshu1422 Can you please see to this idea

**Review by vybhav72954 — APPROVED** [review]

**Comment by vybhav72954** [comment]
@gaurav24072002 Would be adding details to the programs any time soon? or shall I merge this PR for now?

**Comment by gaurav24072002** [comment]
yah !! today I'll add more program dates so merge it by today's night...ok.

**Comment by gaurav24072002** [comment]
Hey !! I have made more changes on it now you can merge..ok

**Review by vybhav72954 — APPROVED** [review]
There are a few things that I am not a fan of, but at least for now, this is a good start. I approve. Thank You for the commits. Keep checking for more issues to solve and programs to participate in. Happy OSS

**Pull request merged**
