### PR TITLE
Changes in new link

### PR DESCRIPTION
**Pull request by agrawalanupam01**
Adding some valuable links,

I am participating in hacktoberfest

### CODE REVIEW

**Comment by vybhav72954** [comment]
Thank you for your contribution. Let me verify them once.

**Comment by vybhav72954** [comment]
@agrawalanupam01 Mozilla Winter of Security was removed in #13 

As far as I know, it stopped in 2017. If you think it's still an ongoing program. Kindly Update your commit with the latest link.

For now, I neither can accept nor merge your PR

**Comment by vybhav72954** [comment]
Though we'll wait, if you can either update us about an ongoing program or can update the current ones, would gladly merge.

**Comment by agrawalanupam01** [comment]
Please check the new pull request.
It has updation in competition links

**Pull request closed without merging**
