### PR TITLE
fixed the dead links

### PR DESCRIPTION
**Pull request by chiragbansal-45**

### CODE REVIEW

**Comment by chiragbansal-45** [comment]
I am able to open the links, but the check says 9 dead links found.

**Review by vybhav72954 — CHANGES_REQUESTED** [review]
All the changes are good to go.

But I have a small request the PR is failing some checks, as you can see [here](https://github.com/deepanshu1422/List-Of-Open-Source-Internships-Programs/runs/2014480794?check_suite_focus=true).

Can you also check those links one, although the status code is 0, so the links most probably are live, but can you just check once, if they are working, I will merge.

**Comment by vybhav72954** [comment]
> I am able to open the links, but the check says 9 dead links found.

I see, that's because of the API issue I guess, never mind those error codes.

**Review by vybhav72954 — APPROVED** [review]
LGTM

**Comment by chiragbansal-45** [comment]
> LGTM

okay! thank you

**Comment by vybhav72954** [comment]
> > LGTM
> 
> okay! thank you

In case you find more Programs that we are missing in the Repo, you are more than welcome to open an issue for that.
You can check other issues as well in case you want to take one.
Happy Open Sourcing

**Pull request merged**
