### PR TITLE
Update in competition links

### PR DESCRIPTION
**Pull request by agrawalanupam01**

### CODE REVIEW

**Comment by vybhav72954** [comment]
Thank you again @agrawalanupam01 

@deepanshu1422 Can you see this PR, considering Google Code-In is a preuniversity program meant for under-17.

**Comment by deepanshu1422** [comment]
I think we should merge this PR as we are not primarily focused on 18+ programmes ...😀

**Comment by vybhav72954** [comment]
Thank You @deepanshu1422 

But sadly I cant merge. Kindly look [at this](https://codein.withgoogle.com/archive/.

According to the website
> The contest was held for 10 years starting in November 2010 and wrapping up the final contest in January 2020.

Considering its no longer active @deepanshu1422 I doubt we should merge this?

A big thanks to @agrawalanupam01 Keep helping us :)

**Comment by vybhav72954** [comment]
Even I wasn't aware, Was reading about it, and then noticed. Was actually going to merge 😞

**Comment by agrawalanupam01** [comment]
I would like to thank both of you. For being kind and your guidance.
I seek some advices from both of. You.
As i want to complete hacktoberfest this year.
Thanks and Regards
Anupam Agrawal

**Pull request closed without merging**
